version: '3.8'

services:
  probe:
    image: ghcr.io/cxiyuan/probe:latest
    container_name: probe
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /root/DeepPupils/logs:/output
    working_dir: /output
    command: >
      zeek -i ens192
      -f "not net 224.0.0.0/4"
      /opt/probe/extend/http-extend.zeek
    restart: unless-stopped
